/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Database.Administrador;
import Database.Clinica;
import Database.Procesos_almacenados;
import Database.Usuarios;
import javax.swing.JPanel;
import Ui.JP001_S1_AFP;
import Ui.JP002_S1_RHP;
import java.awt.Color;
import java.awt.FlowLayout;
import java.net.URL;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import ux.Inicializador;
import ux.Login;
import ux.RegAdmin_JF002;

public class JF_000_S7_GU extends javax.swing.JFrame {

    private Inicializador Inicializador;
    private JP001_S1_AFP Pprueba;

    public JF_000_S7_GU() {
        initComponents();
        this.setLocationRelativeTo(null);
        JPbarra5.setBorder(BorderFactory.createEmptyBorder());
        JPContenido.setBorder(BorderFactory.createEmptyBorder());
        Inicializador = new Inicializador(this);

        URL iconURL = getClass().getResource("/imagenes/IconoMind.png");

        if (iconURL != null) {
            ImageIcon icono = new ImageIcon(iconURL);
            setIconImage(icono.getImage());
        } else {
            System.err.println("No se pudo encontrar el icono.");
        }

    }

    /**
     * This method is called sfrom within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPbarra5 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        JPContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1120, 666));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPbarra5.setBackground(new java.awt.Color(255, 255, 255));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setForeground(new java.awt.Color(44, 102, 110));
        jButton11.setText("-");
        jButton11.setBorder(null);
        jButton11.setFocusPainted(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setForeground(new java.awt.Color(44, 102, 110));
        jButton12.setText("x");
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton12MouseExited(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JPContenido.setMaximumSize(new java.awt.Dimension(1120, 540));
        JPContenido.setMinimumSize(new java.awt.Dimension(1120, 540));
        JPContenido.setName("JPContenido"); // NOI18N
        JPContenido.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout JPbarra5Layout = new javax.swing.GroupLayout(JPbarra5);
        JPbarra5.setLayout(JPbarra5Layout);
        JPbarra5Layout.setHorizontalGroup(
            JPbarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbarra5Layout.createSequentialGroup()
                .addContainerGap(1095, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(JPContenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPbarra5Layout.setVerticalGroup(
            JPbarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbarra5Layout.createSequentialGroup()
                .addGroup(JPbarra5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE))
        );

        getContentPane().add(JPbarra5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton11.setBackground(Color.white);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        jButton11.setBackground(new Color(44, 102, 110));    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseExited
        jButton12.setBackground(Color.white);
    }//GEN-LAST:event_jButton12MouseExited
    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {

    }
    private void jButton12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseEntered
        jButton12.setBackground(new Color(44, 102, 110));
    }//GEN-LAST:event_jButton12MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_000_S7_GU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_000_S7_GU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_000_S7_GU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_000_S7_GU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JF_000_S7_GU vista = new JF_000_S7_GU();
                vista.setLocationRelativeTo(null); // Centra la ventana en la pantalla
                vista.setVisible(true);
                vista.JPContenido.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel JPContenido;
    public javax.swing.JPanel JPbarra5;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    // End of variables declaration//GEN-END:variables

    public void jButton2MouseExited() {

    }

    public void mostrarOcultarPanel(String nombrePanel) {
        Map<String, JPanel> paneles = Inicializador.getPaneles();
        JPanel panel = paneles.get(nombrePanel);

        if (panel != null) {
            ocultarContenido();
            this.JPContenido.add(panel);
            this.validate(); // Esto asegura que los cambios se reflejen correctamente
            this.repaint(); // También puede ser necesario repintar la vista
            System.out.println("Estoy mostrando el panel llamado: " + nombrePanel);
        } else {
            System.out.println("El panel '" + nombrePanel + "' no existe.");
        }
    }

    public void ocultarContenido() {
        this.JPContenido.removeAll();
        this.JPContenido.repaint();
    }

}
