/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;
import keeptoo.KGradientPanel;
import ux.Menu_Administrador;

/**
 *
 * @author 50369
 */
public class JP004_S2_AF extends javax.swing.JPanel {
    
    public Menu_Administrador controlador;

    public Menu_Administrador getControlador() {
        return controlador;
    }

    public void setControlador(Menu_Administrador controlador) {
        this.controlador = controlador;
    }

    public JPanel getJP001_S1_AF() {
        return JP001_S1_AF;
    }

    public void setJP001_S1_AF(JPanel JP001_S1_AF) {
        this.JP001_S1_AF = JP001_S1_AF;
    }

    public JButton getBtn01_JF005_S2_AF() {
        return btn01_JF005_S2_AF;
    }

    public void setBtn01_JF005_S2_AF(JButton btn01_JF005_S2_AF) {
        this.btn01_JF005_S2_AF = btn01_JF005_S2_AF;
    }

    public JButton getBtn03_JF005_S2_AF() {
        return btn03_JF005_S2_AF;
    }

    public void setBtn03_JF005_S2_AF(JButton btn03_JF005_S2_AF) {
        this.btn03_JF005_S2_AF = btn03_JF005_S2_AF;
    }

    public JButton getBtn04_JF005_S2_AF() {
        return btn04_JF005_S2_AF;
    }

    public void setBtn04_JF005_S2_AF(JButton btn04_JF005_S2_AF) {
        this.btn04_JF005_S2_AF = btn04_JF005_S2_AF;
    }

    public JButton getBtn08_JF023_S3_RH() {
        return btn08_JF023_S3_RH;
    }

    public void setBtn08_JF023_S3_RH(JButton btn08_JF023_S3_RH) {
        this.btn08_JF023_S3_RH = btn08_JF023_S3_RH;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public KGradientPanel getkGradientPanel2() {
        return kGradientPanel2;
    }

    public void setkGradientPanel2(KGradientPanel kGradientPanel2) {
        this.kGradientPanel2 = kGradientPanel2;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }
    
   
    
    
    
    
    
    public JP004_S2_AF(Menu_Administrador controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001_S1_AF = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn01_JF005_S2_AF = new javax.swing.JButton();
        btn03_JF005_S2_AF = new javax.swing.JButton();
        btn04_JF005_S2_AF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        btn08_JF023_S3_RH = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        JP001_S1_AF.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_AF.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JP001_S1_AF.setMaximumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_AF.setMinimumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_AF.setPreferredSize(new java.awt.Dimension(1120, 640));
        JP001_S1_AF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("¿Qué desea realizar hoy administrador?");
        JP001_S1_AF.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        btn01_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn01_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnPersonal.png"))); // NOI18N
        btn01_JF005_S2_AF.setBorderPainted(false);
        btn01_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn01_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 150, 180));

        btn03_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn03_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAnuncios.png"))); // NOI18N
        btn03_JF005_S2_AF.setBorderPainted(false);
        btn03_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn03_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 150, 180));

        btn04_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn04_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSoli.png"))); // NOI18N
        btn04_JF005_S2_AF.setBorderPainted(false);
        btn04_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn04_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 170, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        JP001_S1_AF.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 170, 90));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));

        btn08_JF023_S3_RH.setBackground(new java.awt.Color(0, 153, 153));
        btn08_JF023_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log out.png"))); // NOI18N
        btn08_JF023_S3_RH.setBorderPainted(false);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(btn08_JF023_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn08_JF023_S3_RH, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        JP001_S1_AF.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1230, 80));

        add(JP001_S1_AF, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn01_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01_JF005_S2_AFActionPerformed
        
    }//GEN-LAST:event_btn01_JF005_S2_AFActionPerformed

    private void btn03_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03_JF005_S2_AFActionPerformed
       
    }//GEN-LAST:event_btn03_JF005_S2_AFActionPerformed

    private void btn04_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04_JF005_S2_AFActionPerformed
       
    }//GEN-LAST:event_btn04_JF005_S2_AFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel JP001_S1_AF;
    public javax.swing.JButton btn01_JF005_S2_AF;
    public javax.swing.JButton btn03_JF005_S2_AF;
    public javax.swing.JButton btn04_JF005_S2_AF;
    public javax.swing.JButton btn08_JF023_S3_RH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
