/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import keeptoo.KGradientPanel;

/**
 *
 * @author LENOVO
 */
public class JP005_NumTel_S2_RH extends javax.swing.JPanel {

    public JButton getBtn1_JF005_S2_RH() {
        return Btn1_JF005_S2_RH;
    }

    public void setBtn1_JF005_S2_RH(JButton Btn1_JF005_S2_RH) {
        this.Btn1_JF005_S2_RH = Btn1_JF005_S2_RH;
    }

    public JButton getBtn2_JF005_S2_RH() {
        return Btn2_JF005_S2_RH;
    }

    public void setBtn2_JF005_S2_RH(JButton Btn2_JF005_S2_RH) {
        this.Btn2_JF005_S2_RH = Btn2_JF005_S2_RH;
    }

    public JPanel getJP001_S1_RH() {
        return JP001_S1_RH;
    }

    public void setJP001_S1_RH(JPanel JP001_S1_RH) {
        this.JP001_S1_RH = JP001_S1_RH;
    }

    public JTextField getTxtTelefonoRegister_JF005_S2_RH() {
        return TxtTelefonoRegister_JF005_S2_RH;
    }

    public void setTxtTelefonoRegister_JF005_S2_RH(JTextField TxtTelefonoRegister_JF005_S2_RH) {
        this.TxtTelefonoRegister_JF005_S2_RH = TxtTelefonoRegister_JF005_S2_RH;
    }

    public JButton getBtn3_JF005_S2_RH() {
        return btn3_JF005_S2_RH;
    }

    public void setBtn3_JF005_S2_RH(JButton btn3_JF005_S2_RH) {
        this.btn3_JF005_S2_RH = btn3_JF005_S2_RH;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public KGradientPanel getkGradientPanel1() {
        return kGradientPanel1;
    }

    public void setkGradientPanel1(KGradientPanel kGradientPanel1) {
        this.kGradientPanel1 = kGradientPanel1;
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    public JP005_NumTel_S2_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001_S1_RH = new javax.swing.JPanel();
        Btn2_JF005_S2_RH = new javax.swing.JButton();
        Btn1_JF005_S2_RH = new javax.swing.JButton();
        btn3_JF005_S2_RH = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtTelefonoRegister_JF005_S2_RH = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        JP001_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_RH.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JP001_S1_RH.setForeground(new java.awt.Color(0, 102, 102));
        JP001_S1_RH.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JP001_S1_RH.setMaximumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_RH.setMinimumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_RH.setPreferredSize(new java.awt.Dimension(1120, 640));

        Btn2_JF005_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn2_JF005_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarse2.png"))); // NOI18N
        Btn2_JF005_S2_RH.setText("Registrarse");
        Btn2_JF005_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Btn2_JF005_S2_RH.setBorderPainted(false);
        Btn2_JF005_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2_JF005_S2_RH.setInheritsPopupMenu(true);

        Btn1_JF005_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn1_JF005_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIngresar2.png"))); // NOI18N
        Btn1_JF005_S2_RH.setText("Ingresar");
        Btn1_JF005_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 50, true));
        Btn1_JF005_S2_RH.setBorderPainted(false);
        Btn1_JF005_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn1_JF005_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1_JF005_S2_RHActionPerformed(evt);
            }
        });

        btn3_JF005_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn3_JF005_S2_RH.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btn3_JF005_S2_RH.setForeground(new java.awt.Color(0, 102, 102));
        btn3_JF005_S2_RH.setText("¿Quieres probar otro método de recuperación?");
        btn3_JF005_S2_RH.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Elige el número de teléfono con el que te asociaste");

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogitoGrande.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 430, 200));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("RECUPERA TU CONTRASEÑA");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("<html> Sigue las siguientes indicaciones para recuperar tu contraseña <br>    ");

        TxtTelefonoRegister_JF005_S2_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TxtTelefonoRegister_JF005_S2_RH.setForeground(new java.awt.Color(153, 153, 153));
        TxtTelefonoRegister_JF005_S2_RH.setText("Número de telefono registrado");
        TxtTelefonoRegister_JF005_S2_RH.setToolTipText("");
        TxtTelefonoRegister_JF005_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TxtTelefonoRegister_JF005_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtTelefonoRegister_JF005_S2_RH.setDoubleBuffered(true);
        TxtTelefonoRegister_JF005_S2_RH.setDragEnabled(true);
        TxtTelefonoRegister_JF005_S2_RH.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        TxtTelefonoRegister_JF005_S2_RH.setSelectionColor(new java.awt.Color(0, 0, 0));
        TxtTelefonoRegister_JF005_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelefonoRegister_JF005_S2_RHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JP001_S1_RHLayout = new javax.swing.GroupLayout(JP001_S1_RH);
        JP001_S1_RH.setLayout(JP001_S1_RHLayout);
        JP001_S1_RHLayout.setHorizontalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(TxtTelefonoRegister_JF005_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(131, 131, 131))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                                .addComponent(btn3_JF005_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                                .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn2_JF005_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn1_JF005_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(160, 160, 160))))))
        );
        JP001_S1_RHLayout.setVerticalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTelefonoRegister_JF005_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(Btn1_JF005_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn2_JF005_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn3_JF005_S2_RH)
                .addContainerGap(163, Short.MAX_VALUE))
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(JP001_S1_RH, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TxtTelefonoRegister_JF005_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelefonoRegister_JF005_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelefonoRegister_JF005_S2_RHActionPerformed

    private void Btn1_JF005_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1_JF005_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1_JF005_S2_RHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF005_S2_RH;
    public javax.swing.JButton Btn2_JF005_S2_RH;
    public javax.swing.JPanel JP001_S1_RH;
    public javax.swing.JTextField TxtTelefonoRegister_JF005_S2_RH;
    private javax.swing.JButton btn3_JF005_S2_RH;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
