/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import keeptoo.KGradientPanel;
import ux.CreacionDeAnuncios;
import ux.PanelesInicializador;
import ux.VisualizarNotas;

/**
 *
 * @author LENOVO
 */
public class JP006_S2_AF extends javax.swing.JPanel {
    
    
    private CreacionDeAnuncios controlador;
    private PanelesInicializador str;

    public CreacionDeAnuncios getControlador() {
        return controlador;
    }

    public void setControlador(CreacionDeAnuncios controlador) {
        this.controlador = controlador;
    }

    public PanelesInicializador getStr() {
        return str;
    }

    public void setStr(PanelesInicializador str) {
        this.str = str;
    }

    public JButton getBtn2_JF006_S2_AF() {
        return Btn2_JF006_S2_AF;
    }

    public void setBtn2_JF006_S2_AF(JButton Btn2_JF006_S2_AF) {
        this.Btn2_JF006_S2_AF = Btn2_JF006_S2_AF;
    }

    public JButton getBtn3_JF006_S2_AF() {
        return Btn3_JF006_S2_AF;
    }

    public void setBtn3_JF006_S2_AF(JButton Btn3_JF006_S2_AF) {
        this.Btn3_JF006_S2_AF = Btn3_JF006_S2_AF;
    }

    public JButton getBtn001_JF006_S2_AF() {
        return btn001_JF006_S2_AF;
    }

    public void setBtn001_JF006_S2_AF(JButton btn001_JF006_S2_AF) {
        this.btn001_JF006_S2_AF = btn001_JF006_S2_AF;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public KGradientPanel getkGradientPanel2() {
        return kGradientPanel2;
    }

    public void setkGradientPanel2(KGradientPanel kGradientPanel2) {
        this.kGradientPanel2 = kGradientPanel2;
    }
    
    
    
    
    
    
    
    
    
    

    public JP006_S2_AF(CreacionDeAnuncios controlador) {
        initComponents();
        this.controlador = controlador;
        
        str = new PanelesInicializador();
        
         // Establecer el valor de str aquí después de haberlo creado
        str.setJP006_S2_AF(this);
    }
    
    public JP006_S2_AF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn001_JF006_S2_AF = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        Btn3_JF006_S2_AF = new javax.swing.JButton();
        Btn2_JF006_S2_AF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 540));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 540));

        btn001_JF006_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn001_JF006_S2_AF.setForeground(new java.awt.Color(0, 102, 102));
        btn001_JF006_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uim_clinic-medical (3).png"))); // NOI18N
        btn001_JF006_S2_AF.setBorder(null);
        btn001_JF006_S2_AF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N
        jLabel4.setText("jLabel3");

        kGradientPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(200, 232, 232));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        Btn3_JF006_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        Btn3_JF006_S2_AF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Btn3_JF006_S2_AF.setForeground(new java.awt.Color(51, 51, 51));
        Btn3_JF006_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DeleteAds.png"))); // NOI18N
        Btn3_JF006_S2_AF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 50, true));
        Btn3_JF006_S2_AF.setBorderPainted(false);
        Btn3_JF006_S2_AF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn3_JF006_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3_JF006_S2_AFActionPerformed(evt);
            }
        });

        Btn2_JF006_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        Btn2_JF006_S2_AF.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Btn2_JF006_S2_AF.setForeground(new java.awt.Color(51, 51, 51));
        Btn2_JF006_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AddS.png"))); // NOI18N
        Btn2_JF006_S2_AF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        Btn2_JF006_S2_AF.setBorderPainted(false);
        Btn2_JF006_S2_AF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2_JF006_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2_JF006_S2_AFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Creación de anuncios");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/li.PNG"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(1120, 540));
        jLabel5.setMinimumSize(new java.awt.Dimension(1120, 540));
        jLabel5.setPreferredSize(new java.awt.Dimension(1120, 540));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn001_JF006_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(291, 291, 291)))
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn2_JF006_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn3_JF006_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn001_JF006_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)))
                .addGap(104, 104, 104)
                .addComponent(Btn2_JF006_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Btn3_JF006_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void Btn3_JF006_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3_JF006_S2_AFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn3_JF006_S2_AFActionPerformed

    private void Btn2_JF006_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2_JF006_S2_AFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn2_JF006_S2_AFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn2_JF006_S2_AF;
    public javax.swing.JButton Btn3_JF006_S2_AF;
    public javax.swing.JButton btn001_JF006_S2_AF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
