/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JTextField;
import ux.RecGmail;
import ux.PanelesInicializador;
import Ui.JP003_2_S1_RH;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import keeptoo.KGradientPanel;
import ux.Hints;
import ux.LimiteCaracteres;

/**
 *
 * @author 50369
 */
public class JP003_2_S1_RH extends javax.swing.JPanel {
    
    private JP003_2_S1_RH panel;
    private RecGmail controlador;
    private PanelesInicializador str;
    private Hints hint;
    private LimiteCaracteres Limite;

    public JP003_2_S1_RH getPanel() {
        return panel;
    }

    public void setPanel(JP003_2_S1_RH panel) {
        this.panel = panel;
    }

    public RecGmail getControlador() {
        return controlador;
    }

    public void setControlador(RecGmail controlador) {
        this.controlador = controlador;
    }

    public PanelesInicializador getStr() {
        return str;
    }

    public void setStr(PanelesInicializador str) {
        this.str = str;
    }

    public Hints getHint() {
        return hint;
    }

    public void setHint(Hints hint) {
        this.hint = hint;
    }

    public LimiteCaracteres getLimite() {
        return Limite;
    }

    public void setLimite(LimiteCaracteres Limite) {
        this.Limite = Limite;
    }

    public JButton getBtn1_JF003_2_S1_RH() {
        return Btn1_JF003_2_S1_RH;
    }

    public void setBtn1_JF003_2_S1_RH(JButton Btn1_JF003_2_S1_RH) {
        this.Btn1_JF003_2_S1_RH = Btn1_JF003_2_S1_RH;
    }

    public JButton getBtn2_JF003_2_S1_RH() {
        return Btn2_JF003_2_S1_RH;
    }

    public void setBtn2_JF003_2_S1_RH(JButton Btn2_JF003_2_S1_RH) {
        this.Btn2_JF003_2_S1_RH = Btn2_JF003_2_S1_RH;
    }

    public JButton getBtn3_JF003_2_S1_RH() {
        return Btn3_JF003_2_S1_RH;
    }

    public void setBtn3_JF003_2_S1_RH(JButton Btn3_JF003_2_S1_RH) {
        this.Btn3_JF003_2_S1_RH = Btn3_JF003_2_S1_RH;
    }

    public JPanel getJP001_S1_RH() {
        return JP001_S1_RH;
    }

    public void setJP001_S1_RH(JPanel JP001_S1_RH) {
        this.JP001_S1_RH = JP001_S1_RH;
    }

    public JPasswordField getPassField_ConfirmarContra_JF003_3_S1_RH1() {
        return PassField_ConfirmarContra_JF003_3_S1_RH1;
    }

    public void setPassField_ConfirmarContra_JF003_3_S1_RH1(JPasswordField PassField_ConfirmarContra_JF003_3_S1_RH1) {
        this.PassField_ConfirmarContra_JF003_3_S1_RH1 = PassField_ConfirmarContra_JF003_3_S1_RH1;
    }

    public JTextField getTxtCodigoCorreo_JF003_2_S1_RH2() {
        return TxtCodigoCorreo_JF003_2_S1_RH2;
    }

    public void setTxtCodigoCorreo_JF003_2_S1_RH2(JTextField TxtCodigoCorreo_JF003_2_S1_RH2) {
        this.TxtCodigoCorreo_JF003_2_S1_RH2 = TxtCodigoCorreo_JF003_2_S1_RH2;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public KGradientPanel getkGradientPanel1() {
        return kGradientPanel1;
    }

    public void setkGradientPanel1(KGradientPanel kGradientPanel1) {
        this.kGradientPanel1 = kGradientPanel1;
    }
    
    
    
    
    /**
     * Creates new form JP003_2_S1_RH
     */
    public JP003_2_S1_RH(RecGmail controlador) {
        str = new PanelesInicializador();
        this.controlador = controlador;
        initComponents();
        LimiteCaracteres limiteCodigoCorreo = new LimiteCaracteres(TxtCodigoCorreo_JF003_2_S1_RH2, 0, 50);
        hint.addHint(getTxtCodigoCorreo_JF003_2_S1_RH2(), "Ingresa el código enviado al correo asociado");

       
        
        
        // Establecer el valor de str aquí después de haberlo creado
        str.setJP003_2_S1_RH(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001_S1_RH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtCodigoCorreo_JF003_2_S1_RH2 = new javax.swing.JTextField();
        Btn1_JF003_2_S1_RH = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Btn2_JF003_2_S1_RH = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        PassField_ConfirmarContra_JF003_3_S1_RH1 = new javax.swing.JPasswordField();
        Btn3_JF003_2_S1_RH = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        JP001_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_RH.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JP001_S1_RH.setForeground(new java.awt.Color(0, 102, 102));
        JP001_S1_RH.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JP001_S1_RH.setMaximumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_RH.setMinimumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_RH.setPreferredSize(new java.awt.Dimension(1120, 640));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("RECUPERA TU CONTRASEÑA");

        TxtCodigoCorreo_JF003_2_S1_RH2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TxtCodigoCorreo_JF003_2_S1_RH2.setForeground(new java.awt.Color(153, 153, 153));
        TxtCodigoCorreo_JF003_2_S1_RH2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TxtCodigoCorreo_JF003_2_S1_RH2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtCodigoCorreo_JF003_2_S1_RH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoCorreo_JF003_2_S1_RH2ActionPerformed(evt);
            }
        });

        Btn1_JF003_2_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF003_2_S1_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn1_JF003_2_S1_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF003_2_S1_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIngresar3Chikito.png"))); // NOI18N
        Btn1_JF003_2_S1_RH.setText("Ingresar");
        Btn1_JF003_2_S1_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 50, true));
        Btn1_JF003_2_S1_RH.setBorderPainted(false);
        Btn1_JF003_2_S1_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn1_JF003_2_S1_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1_JF003_2_S1_RHActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Ingresa el código enviado al correo asociado");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("<html> Sigue las siguientes indicaciones para recuperar tu contraseña <br>    ");

        Btn2_JF003_2_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn2_JF003_2_S1_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn2_JF003_2_S1_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn2_JF003_2_S1_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarse2.png"))); // NOI18N
        Btn2_JF003_2_S1_RH.setText("Registrarse");
        Btn2_JF003_2_S1_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Btn2_JF003_2_S1_RH.setBorderPainted(false);
        Btn2_JF003_2_S1_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2_JF003_2_S1_RH.setInheritsPopupMenu(true);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Confirmar nueva contraseña");

        PassField_ConfirmarContra_JF003_3_S1_RH1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        PassField_ConfirmarContra_JF003_3_S1_RH1.setForeground(new java.awt.Color(153, 153, 153));
        PassField_ConfirmarContra_JF003_3_S1_RH1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PassField_ConfirmarContra_JF003_3_S1_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PassField_ConfirmarContra_JF003_3_S1_RH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassField_ConfirmarContra_JF003_3_S1_RH1ActionPerformed(evt);
            }
        });

        Btn3_JF003_2_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn3_JF003_2_S1_RH.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Btn3_JF003_2_S1_RH.setForeground(new java.awt.Color(0, 102, 102));
        Btn3_JF003_2_S1_RH.setText("¿Quieres probar otro método de recuperación?");
        Btn3_JF003_2_S1_RH.setBorder(null);
        Btn3_JF003_2_S1_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn3_JF003_2_S1_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3_JF003_2_S1_RHActionPerformed(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogitoGrande.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 430, 200));

        javax.swing.GroupLayout JP001_S1_RHLayout = new javax.swing.GroupLayout(JP001_S1_RH);
        JP001_S1_RH.setLayout(JP001_S1_RHLayout);
        JP001_S1_RHLayout.setHorizontalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCodigoCorreo_JF003_2_S1_RH2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PassField_ConfirmarContra_JF003_3_S1_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))))
                        .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Btn1_JF003_2_S1_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(Btn2_JF003_2_S1_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(46, 46, 46)))
                    .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel4))
                    .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(Btn3_JF003_2_S1_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JP001_S1_RHLayout.setVerticalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCodigoCorreo_JF003_2_S1_RH2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PassField_ConfirmarContra_JF003_3_S1_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Btn1_JF003_2_S1_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn2_JF003_2_S1_RH)
                .addGap(23, 23, 23)
                .addComponent(Btn3_JF003_2_S1_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(JP001_S1_RH, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigoCorreo_JF003_2_S1_RH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoCorreo_JF003_2_S1_RH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoCorreo_JF003_2_S1_RH2ActionPerformed

    private void Btn1_JF003_2_S1_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1_JF003_2_S1_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1_JF003_2_S1_RHActionPerformed

    private void PassField_ConfirmarContra_JF003_3_S1_RH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassField_ConfirmarContra_JF003_3_S1_RH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassField_ConfirmarContra_JF003_3_S1_RH1ActionPerformed

    private void Btn3_JF003_2_S1_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3_JF003_2_S1_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn3_JF003_2_S1_RHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF003_2_S1_RH;
    public javax.swing.JButton Btn2_JF003_2_S1_RH;
    private javax.swing.JButton Btn3_JF003_2_S1_RH;
    private javax.swing.JPanel JP001_S1_RH;
    public javax.swing.JPasswordField PassField_ConfirmarContra_JF003_3_S1_RH1;
    public javax.swing.JTextField TxtCodigoCorreo_JF003_2_S1_RH2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
