/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import keeptoo.KGradientPanel;

/**
 *
 * @author LENOVO
 */
public class JP005_S1_RHP extends javax.swing.JPanel {

    public JButton getBtn1_JF005_2_S2_RH() {
        return Btn1_JF005_2_S2_RH;
    }

    public void setBtn1_JF005_2_S2_RH(JButton Btn1_JF005_2_S2_RH) {
        this.Btn1_JF005_2_S2_RH = Btn1_JF005_2_S2_RH;
    }

    public JButton getBtn2_JF005_2_S2_RH() {
        return Btn2_JF005_2_S2_RH;
    }

    public void setBtn2_JF005_2_S2_RH(JButton Btn2_JF005_2_S2_RH) {
        this.Btn2_JF005_2_S2_RH = Btn2_JF005_2_S2_RH;
    }

    public JPanel getJP001_S1_RH() {
        return JP001_S1_RH;
    }

    public void setJP001_S1_RH(JPanel JP001_S1_RH) {
        this.JP001_S1_RH = JP001_S1_RH;
    }

    public JTextField getTxtCodigoTel_JF005_2_S2_RH() {
        return TxtCodigoTel_JF005_2_S2_RH;
    }

    public void setTxtCodigoTel_JF005_2_S2_RH(JTextField TxtCodigoTel_JF005_2_S2_RH) {
        this.TxtCodigoTel_JF005_2_S2_RH = TxtCodigoTel_JF005_2_S2_RH;
    }

    public JButton getBtn3_JF005_2_S2_RH() {
        return btn3_JF005_2_S2_RH;
    }

    public void setBtn3_JF005_2_S2_RH(JButton btn3_JF005_2_S2_RH) {
        this.btn3_JF005_2_S2_RH = btn3_JF005_2_S2_RH;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public KGradientPanel getkGradientPanel1() {
        return kGradientPanel1;
    }

    public void setkGradientPanel1(KGradientPanel kGradientPanel1) {
        this.kGradientPanel1 = kGradientPanel1;
    }

    
    
    
    
    
    
    public JP005_S1_RHP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001_S1_RH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtCodigoTel_JF005_2_S2_RH = new javax.swing.JTextField();
        Btn2_JF005_2_S2_RH = new javax.swing.JButton();
        Btn1_JF005_2_S2_RH = new javax.swing.JButton();
        btn3_JF005_2_S2_RH = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        JP001_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_RH.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JP001_S1_RH.setForeground(new java.awt.Color(0, 102, 102));
        JP001_S1_RH.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JP001_S1_RH.setMaximumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_RH.setMinimumSize(new java.awt.Dimension(1120, 640));
        JP001_S1_RH.setPreferredSize(new java.awt.Dimension(1120, 640));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("RECUPERA TU CONTRASEÑA");

        TxtCodigoTel_JF005_2_S2_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TxtCodigoTel_JF005_2_S2_RH.setForeground(new java.awt.Color(153, 153, 153));
        TxtCodigoTel_JF005_2_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TxtCodigoTel_JF005_2_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtCodigoTel_JF005_2_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoTel_JF005_2_S2_RHActionPerformed(evt);
            }
        });

        Btn2_JF005_2_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_2_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn2_JF005_2_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_2_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarse2.png"))); // NOI18N
        Btn2_JF005_2_S2_RH.setText("Registrarse");
        Btn2_JF005_2_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Btn2_JF005_2_S2_RH.setBorderPainted(false);
        Btn2_JF005_2_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2_JF005_2_S2_RH.setInheritsPopupMenu(true);

        Btn1_JF005_2_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_2_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn1_JF005_2_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_2_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIngresar2.png"))); // NOI18N
        Btn1_JF005_2_S2_RH.setText("Ingresar");
        Btn1_JF005_2_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 50, true));
        Btn1_JF005_2_S2_RH.setBorderPainted(false);
        Btn1_JF005_2_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn1_JF005_2_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1_JF005_2_S2_RHActionPerformed(evt);
            }
        });

        btn3_JF005_2_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn3_JF005_2_S2_RH.setForeground(new java.awt.Color(0, 102, 102));
        btn3_JF005_2_S2_RH.setText("¿Quieres probar otro método de recuperación?");
        btn3_JF005_2_S2_RH.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("<html> Sigue las siguientes indicaciones para recuperar tu contraseña <br>    ");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Ingresa el código enviado al número de teléfono  asociado");

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogitoGrande.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JP001_S1_RHLayout = new javax.swing.GroupLayout(JP001_S1_RH);
        JP001_S1_RH.setLayout(JP001_S1_RHLayout);
        JP001_S1_RHLayout.setHorizontalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn3_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn1_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn2_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TxtCodigoTel_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44))
                            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JP001_S1_RHLayout.setVerticalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCodigoTel_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(Btn1_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn2_JF005_2_S2_RH)
                .addGap(23, 23, 23)
                .addComponent(btn3_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(JP001_S1_RH, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigoTel_JF005_2_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoTel_JF005_2_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoTel_JF005_2_S2_RHActionPerformed

    private void Btn1_JF005_2_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1_JF005_2_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1_JF005_2_S2_RHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF005_2_S2_RH;
    public javax.swing.JButton Btn2_JF005_2_S2_RH;
    public javax.swing.JPanel JP001_S1_RH;
    public javax.swing.JTextField TxtCodigoTel_JF005_2_S2_RH;
    private javax.swing.JButton btn3_JF005_2_S2_RH;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
