/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import keeptoo.KGradientPanel;

/**
 *
 * @author LENOVO
 */
public class JP005_3_S2_RH extends javax.swing.JPanel {

    public JButton getBtn1_JF005_3_S2_RH() {
        return Btn1_JF005_3_S2_RH;
    }

    public void setBtn1_JF005_3_S2_RH(JButton Btn1_JF005_3_S2_RH) {
        this.Btn1_JF005_3_S2_RH = Btn1_JF005_3_S2_RH;
    }

    public JButton getBtn2_JF005_3_S2_RH() {
        return Btn2_JF005_3_S2_RH;
    }

    public void setBtn2_JF005_3_S2_RH(JButton Btn2_JF005_3_S2_RH) {
        this.Btn2_JF005_3_S2_RH = Btn2_JF005_3_S2_RH;
    }

    public JPanel getJP001_S1_RH() {
        return JP001_S1_RH;
    }

    public void setJP001_S1_RH(JPanel JP001_S1_RH) {
        this.JP001_S1_RH = JP001_S1_RH;
    }

    public JPasswordField getPassField2_ConfirmarContra_JF002_3_S2_RH1() {
        return PassField2_ConfirmarContra_JF002_3_S2_RH1;
    }

    public void setPassField2_ConfirmarContra_JF002_3_S2_RH1(JPasswordField PassField2_ConfirmarContra_JF002_3_S2_RH1) {
        this.PassField2_ConfirmarContra_JF002_3_S2_RH1 = PassField2_ConfirmarContra_JF002_3_S2_RH1;
    }

    public JPasswordField getPassField_ConfirmarContra_JF003_3_S2_RH1() {
        return PassField_ConfirmarContra_JF003_3_S2_RH1;
    }

    public void setPassField_ConfirmarContra_JF003_3_S2_RH1(JPasswordField PassField_ConfirmarContra_JF003_3_S2_RH1) {
        this.PassField_ConfirmarContra_JF003_3_S2_RH1 = PassField_ConfirmarContra_JF003_3_S2_RH1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public KGradientPanel getkGradientPanel1() {
        return kGradientPanel1;
    }

    public void setkGradientPanel1(KGradientPanel kGradientPanel1) {
        this.kGradientPanel1 = kGradientPanel1;
    }

    
    
    
    
    
    
    
    
    
    
    
    
    public JP005_3_S2_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001_S1_RH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PassField2_ConfirmarContra_JF002_3_S2_RH1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        Btn1_JF005_3_S2_RH = new javax.swing.JButton();
        Btn2_JF005_3_S2_RH = new javax.swing.JButton();
        PassField_ConfirmarContra_JF003_3_S2_RH1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 660));
        setMinimumSize(new java.awt.Dimension(1120, 660));
        setPreferredSize(new java.awt.Dimension(1120, 660));

        JP001_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_RH.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JP001_S1_RH.setForeground(new java.awt.Color(0, 102, 102));
        JP001_S1_RH.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JP001_S1_RH.setMaximumSize(new java.awt.Dimension(1120, 660));
        JP001_S1_RH.setMinimumSize(new java.awt.Dimension(1120, 660));
        JP001_S1_RH.setPreferredSize(new java.awt.Dimension(1120, 660));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("RECUPERA TU CONTRASEÑA");

        PassField2_ConfirmarContra_JF002_3_S2_RH1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        PassField2_ConfirmarContra_JF002_3_S2_RH1.setForeground(new java.awt.Color(153, 153, 153));
        PassField2_ConfirmarContra_JF002_3_S2_RH1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PassField2_ConfirmarContra_JF002_3_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PassField2_ConfirmarContra_JF002_3_S2_RH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassField2_ConfirmarContra_JF002_3_S2_RH1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Confirmar nueva contraseña");

        Btn1_JF005_3_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_3_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn1_JF005_3_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_3_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIngresar2.png"))); // NOI18N
        Btn1_JF005_3_S2_RH.setText("Ingresar");
        Btn1_JF005_3_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 50, true));
        Btn1_JF005_3_S2_RH.setBorderPainted(false);
        Btn1_JF005_3_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn1_JF005_3_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1_JF005_3_S2_RHActionPerformed(evt);
            }
        });

        Btn2_JF005_3_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_3_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn2_JF005_3_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_3_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarse2.png"))); // NOI18N
        Btn2_JF005_3_S2_RH.setText("Registrarse");
        Btn2_JF005_3_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Btn2_JF005_3_S2_RH.setBorderPainted(false);
        Btn2_JF005_3_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2_JF005_3_S2_RH.setInheritsPopupMenu(true);

        PassField_ConfirmarContra_JF003_3_S2_RH1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        PassField_ConfirmarContra_JF003_3_S2_RH1.setForeground(new java.awt.Color(153, 153, 153));
        PassField_ConfirmarContra_JF003_3_S2_RH1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PassField_ConfirmarContra_JF003_3_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PassField_ConfirmarContra_JF003_3_S2_RH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassField_ConfirmarContra_JF003_3_S2_RH1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Ingresa una nueva contraseña");

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogitoGrande.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 430, 200));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setText("Sigue los  pasos para recuperar tu contraseña");

        javax.swing.GroupLayout JP001_S1_RHLayout = new javax.swing.GroupLayout(JP001_S1_RH);
        JP001_S1_RH.setLayout(JP001_S1_RHLayout);
        JP001_S1_RHLayout.setHorizontalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel11)
                    .addComponent(PassField2_ConfirmarContra_JF002_3_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn1_JF005_3_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn2_JF005_3_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(PassField_ConfirmarContra_JF003_3_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JP001_S1_RHLayout.setVerticalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassField2_ConfirmarContra_JF002_3_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassField_ConfirmarContra_JF003_3_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Btn1_JF005_3_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn2_JF005_3_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP001_S1_RH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP001_S1_RH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PassField2_ConfirmarContra_JF002_3_S2_RH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassField2_ConfirmarContra_JF002_3_S2_RH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassField2_ConfirmarContra_JF002_3_S2_RH1ActionPerformed

    private void Btn1_JF005_3_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1_JF005_3_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1_JF005_3_S2_RHActionPerformed

    private void PassField_ConfirmarContra_JF003_3_S2_RH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassField_ConfirmarContra_JF003_3_S2_RH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassField_ConfirmarContra_JF003_3_S2_RH1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF005_3_S2_RH;
    public javax.swing.JButton Btn2_JF005_3_S2_RH;
    private javax.swing.JPanel JP001_S1_RH;
    public javax.swing.JPasswordField PassField2_ConfirmarContra_JF002_3_S2_RH1;
    public javax.swing.JPasswordField PassField_ConfirmarContra_JF003_3_S2_RH1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
