/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import ux.AcercaDeLaClinica;

/**
 *
 * @author 50369
 */
public class JP0013_S2_RH extends javax.swing.JPanel {

    private AcercaDeLaClinica controlador;

    public JButton getBtn001_JF013_S2_RH() {
        return Btn001_JF013_S2_RH;
    }

    public void setBtn001_JF013_S2_RH(JButton Btn001_JF013_S2_RH) {
        this.Btn001_JF013_S2_RH = Btn001_JF013_S2_RH;
    }

    public JButton getBtn4_JF013_S2_RH2() {
        return Btn4_JF013_S2_RH2;
    }

    public void setBtn4_JF013_S2_RH2(JButton Btn4_JF013_S2_RH2) {
        this.Btn4_JF013_S2_RH2 = Btn4_JF013_S2_RH2;
    }

    public JLabel getJLFoto_JF013_S2_RH() {
        return JLFoto_JF013_S2_RH;
    }

    public void setJLFoto_JF013_S2_RH(JLabel JLFoto_JF013_S2_RH) {
        this.JLFoto_JF013_S2_RH = JLFoto_JF013_S2_RH;
    }

    public JTextField getTxUbicacion_JF013_S2_RH() {
        return TxUbicacion_JF013_S2_RH;
    }

    public void setTxUbicacion_JF013_S2_RH(JTextField TxUbicacion_JF013_S2_RH) {
        this.TxUbicacion_JF013_S2_RH = TxUbicacion_JF013_S2_RH;
    }

    public JTextField getTxtDescripcion2_JF013_S2_RH() {
        return TxtDescripcion2_JF013_S2_RH;
    }

    public void setTxtDescripcion2_JF013_S2_RH(JTextField TxtDescripcion2_JF013_S2_RH) {
        this.TxtDescripcion2_JF013_S2_RH = TxtDescripcion2_JF013_S2_RH;
    }

    public JTextField getTxtDescripcion_JF013_S2_RH1() {
        return TxtDescripcion_JF013_S2_RH1;
    }

    public void setTxtDescripcion_JF013_S2_RH1(JTextField TxtDescripcion_JF013_S2_RH1) {
        this.TxtDescripcion_JF013_S2_RH1 = TxtDescripcion_JF013_S2_RH1;
    }

    public JTextField getTxtTitulo_JF013_S2_RH() {
        return TxtTitulo_JF013_S2_RH;
    }

    public void setTxtTitulo_JF013_S2_RH(JTextField TxtTitulo_JF013_S2_RH) {
        this.TxtTitulo_JF013_S2_RH = TxtTitulo_JF013_S2_RH;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }
    
   
    
    public JP0013_S2_RH(AcercaDeLaClinica controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn001_JF013_S2_RH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Btn4_JF013_S2_RH2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JLFoto_JF013_S2_RH = new javax.swing.JLabel();
        TxtDescripcion2_JF013_S2_RH = new javax.swing.JTextField();
        TxtTitulo_JF013_S2_RH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxUbicacion_JF013_S2_RH = new javax.swing.JTextField();
        TxtDescripcion_JF013_S2_RH1 = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Btn001_JF013_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn001_JF013_S2_RH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Btn001_JF013_S2_RH.setForeground(new java.awt.Color(0, 102, 102));
        Btn001_JF013_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uim_clinic-medical (3).png"))); // NOI18N
        Btn001_JF013_S2_RH.setBorder(null);
        Btn001_JF013_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Ubicación");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        Btn4_JF013_S2_RH2.setBackground(new java.awt.Color(0, 153, 153));
        Btn4_JF013_S2_RH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EditPencil.png"))); // NOI18N
        Btn4_JF013_S2_RH2.setBorderPainted(false);
        Btn4_JF013_S2_RH2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Acerca de la clínica");

        TxtDescripcion2_JF013_S2_RH.setBackground(new java.awt.Color(0, 153, 153));
        TxtDescripcion2_JF013_S2_RH.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        TxtDescripcion2_JF013_S2_RH.setText("Inserte una descripción adicional acerca de la clinica");
        TxtDescripcion2_JF013_S2_RH.setBorder(null);
        TxtDescripcion2_JF013_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDescripcion2_JF013_S2_RHActionPerformed(evt);
            }
        });

        TxtTitulo_JF013_S2_RH.setBackground(new java.awt.Color(0, 153, 153));
        TxtTitulo_JF013_S2_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TxtTitulo_JF013_S2_RH.setText("Nombre de la clinica");
        TxtTitulo_JF013_S2_RH.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtDescripcion2_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JLFoto_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn4_JF013_S2_RH2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(71, Short.MAX_VALUE)
                    .addComponent(TxtTitulo_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(TxtDescripcion2_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(JLFoto_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn4_JF013_S2_RH2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(TxtTitulo_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(474, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Descripción");

        TxUbicacion_JF013_S2_RH.setBorder(null);

        TxtDescripcion_JF013_S2_RH1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        TxtDescripcion_JF013_S2_RH1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn001_JF013_S2_RH)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(TxUbicacion_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(TxtDescripcion_JF013_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(519, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn001_JF013_S2_RH)
                    .addComponent(jLabel3))
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TxUbicacion_JF013_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(TxtDescripcion_JF013_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDescripcion2_JF013_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDescripcion2_JF013_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDescripcion2_JF013_S2_RHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn001_JF013_S2_RH;
    public javax.swing.JButton Btn4_JF013_S2_RH2;
    public javax.swing.JLabel JLFoto_JF013_S2_RH;
    public javax.swing.JTextField TxUbicacion_JF013_S2_RH;
    public javax.swing.JTextField TxtDescripcion2_JF013_S2_RH;
    public javax.swing.JTextField TxtDescripcion_JF013_S2_RH1;
    public javax.swing.JTextField TxtTitulo_JF013_S2_RH;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
