/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import ux.PanelesInicializador;
import ux.VerSolicitudAprobada;
import ux.VerSolicitudRechazada;

/**
 *
 * @author LENOVO
 */
public class JP019_1_S2_RH extends javax.swing.JPanel {

    
     private VerSolicitudRechazada controlador;
    private PanelesInicializador str;

    public JButton getBtn1_JF019_S2_RH() {
        return Btn1_JF019_S2_RH;
    }

    public void setBtn1_JF019_S2_RH(JButton Btn1_JF019_S2_RH) {
        this.Btn1_JF019_S2_RH = Btn1_JF019_S2_RH;
    }

    public JButton getBtn2_JF019_S2_RH() {
        return Btn2_JF019_S2_RH;
    }

    public void setBtn2_JF019_S2_RH(JButton Btn2_JF019_S2_RH) {
        this.Btn2_JF019_S2_RH = Btn2_JF019_S2_RH;
    }

    public JPanel getJPSolicitud_JP019_S2_RH() {
        return JPSolicitud_JP019_S2_RH;
    }

    public void setJPSolicitud_JP019_S2_RH(JPanel JPSolicitud_JP019_S2_RH) {
        this.JPSolicitud_JP019_S2_RH = JPSolicitud_JP019_S2_RH;
    }

    public JLabel getJlLogo() {
        return JlLogo;
    }

    public void setJlLogo(JLabel JlLogo) {
        this.JlLogo = JlLogo;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
    
        public JLabel getLbNotas() {
        return LbNotas;
    }

    public void setLbNotasText(String texto) {
        this.LbNotas.setText(texto);
    }

    public JLabel getLblAsunto() {
        return LblAsunto;
    }

    public void setLblAsunto(String LblAsunto) {
        this.LblAsunto.setText(LblAsunto);
    }
    
    

    public JP019_1_S2_RH(VerSolicitudRechazada controlador) {
        initComponents();
        this.controlador = controlador;
        
        str = new PanelesInicializador();
        
         // Establecer el valor de str aquí después de haberlo creado
        str.setJP019_1_S2_RH(this);
    }
    
    
    public JP019_1_S2_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn1_JF019_S2_RH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JlLogo = new javax.swing.JLabel();
        JPSolicitud_JP019_S2_RH = new javax.swing.JPanel();
        Btn2_JF019_S2_RH = new javax.swing.JButton();
        LblAsunto = new javax.swing.JLabel();
        LbNotas = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 640));

        Btn1_JF019_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF019_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF019_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector (1).png"))); // NOI18N
        Btn1_JF019_S2_RH.setBorderPainted(false);
        Btn1_JF019_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Esta solicitud la rechazaste");

        JlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        JPSolicitud_JP019_S2_RH.setBackground(new java.awt.Color(246, 246, 246));

        Btn2_JF019_S2_RH.setBackground(new java.awt.Color(246, 246, 246));
        Btn2_JF019_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AprobarS.png"))); // NOI18N
        Btn2_JF019_S2_RH.setBorderPainted(false);
        Btn2_JF019_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblAsunto.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LblAsunto.setText("Asunto");

        LbNotas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LbNotas.setText("jLabel1");
        LbNotas.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout JPSolicitud_JP019_S2_RHLayout = new javax.swing.GroupLayout(JPSolicitud_JP019_S2_RH);
        JPSolicitud_JP019_S2_RH.setLayout(JPSolicitud_JP019_S2_RHLayout);
        JPSolicitud_JP019_S2_RHLayout.setHorizontalGroup(
            JPSolicitud_JP019_S2_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSolicitud_JP019_S2_RHLayout.createSequentialGroup()
                .addGroup(JPSolicitud_JP019_S2_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPSolicitud_JP019_S2_RHLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(Btn2_JF019_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPSolicitud_JP019_S2_RHLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LblAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(JPSolicitud_JP019_S2_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPSolicitud_JP019_S2_RHLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(LbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );
        JPSolicitud_JP019_S2_RHLayout.setVerticalGroup(
            JPSolicitud_JP019_S2_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSolicitud_JP019_S2_RHLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(LblAsunto)
                .addGap(350, 350, 350)
                .addComponent(Btn2_JF019_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(JPSolicitud_JP019_S2_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPSolicitud_JP019_S2_RHLayout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(LbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Btn1_JF019_S2_RH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(268, 268, 268)
                .addComponent(JlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(JPSolicitud_JP019_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Btn1_JF019_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)))
                    .addComponent(JlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(JPSolicitud_JP019_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF019_S2_RH;
    public javax.swing.JButton Btn2_JF019_S2_RH;
    public javax.swing.JPanel JPSolicitud_JP019_S2_RH;
    public javax.swing.JLabel JlLogo;
    public javax.swing.JLabel LbNotas;
    public javax.swing.JLabel LblAsunto;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
