/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import ux.PanelesInicializador;
import ux.VerSolicitudAprobada;

/**
 *
 * @author LENOVO
 */
public class JP017_1_S2_RH extends javax.swing.JPanel {

    private VerSolicitudAprobada controlador;
    private PanelesInicializador str;

    public JButton getBtn1_JF017_S2_RH1() {
        return Btn1_JF017_S2_RH1;
    }

    public void setBtn1_JF017_S2_RH1(JButton Btn1_JF017_S2_RH1) {
        this.Btn1_JF017_S2_RH1 = Btn1_JF017_S2_RH1;
    }

    public JButton getBtn2_JF017_S2_RH1() {
        return Btn2_JF017_S2_RH1;
    }

    public void setBtn2_JF017_S2_RH1(JButton Btn2_JF017_S2_RH1) {
        this.Btn2_JF017_S2_RH1 = Btn2_JF017_S2_RH1;
    }

    public JPanel getJPSolicitud_JP017_S2_RH1() {
        return JPSolicitud_JP017_S2_RH1;
    }

    public void setJPSolicitud_JP017_S2_RH1(JPanel JPSolicitud_JP017_S2_RH1) {
        this.JPSolicitud_JP017_S2_RH1 = JPSolicitud_JP017_S2_RH1;
    }

    public JLabel getJlLogo1() {
        return JlLogo1;
    }

    public JLabel getjLabel2() {
        return LblAsunto;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.LblAsunto = jLabel2;
    }

    public JLabel getLbNotas() {
        return LbNotas;
    }

    public void setLbNotasText(String texto) {
        this.LbNotas.setText(texto);
    }
    

    public JLabel getLblAsunto() {
        return LblAsunto;
    }

    public void setLblAsunto(String LblAsunto) {
        this.LblAsunto.setText(LblAsunto);
    }
    
    public JP017_1_S2_RH(VerSolicitudAprobada controlador) {
        initComponents();
        this.controlador = controlador;

        str = new PanelesInicializador();

        // Establecer el valor de str aquí después de haberlo creado
        str.setJP017_1_S2_RH(this);
    }

    public JP017_1_S2_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Btn1_JF017_S2_RH1 = new javax.swing.JButton();
        JlLogo1 = new javax.swing.JLabel();
        JPSolicitud_JP017_S2_RH1 = new javax.swing.JPanel();
        Btn2_JF017_S2_RH1 = new javax.swing.JButton();
        LblAsunto = new javax.swing.JLabel();
        JPSolicitud_JP017_S2_RH2 = new javax.swing.JPanel();
        LbNotas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel2.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 640));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Btn1_JF017_S2_RH1.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH1.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector (1).png"))); // NOI18N
        Btn1_JF017_S2_RH1.setBorderPainted(false);
        Btn1_JF017_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        JlLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        JPSolicitud_JP017_S2_RH1.setBackground(new java.awt.Color(246, 246, 246));
        JPSolicitud_JP017_S2_RH1.setMaximumSize(new java.awt.Dimension(1120, 540));

        Btn2_JF017_S2_RH1.setBackground(new java.awt.Color(246, 246, 246));
        Btn2_JF017_S2_RH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rechazarS.png"))); // NOI18N
        Btn2_JF017_S2_RH1.setBorderPainted(false);
        Btn2_JF017_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblAsunto.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LblAsunto.setText("Asunto");

        JPSolicitud_JP017_S2_RH2.setBackground(new java.awt.Color(204, 204, 204));
        JPSolicitud_JP017_S2_RH2.setMaximumSize(new java.awt.Dimension(1120, 540));

        LbNotas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LbNotas.setText("jLabel1");
        LbNotas.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout JPSolicitud_JP017_S2_RH2Layout = new javax.swing.GroupLayout(JPSolicitud_JP017_S2_RH2);
        JPSolicitud_JP017_S2_RH2.setLayout(JPSolicitud_JP017_S2_RH2Layout);
        JPSolicitud_JP017_S2_RH2Layout.setHorizontalGroup(
            JPSolicitud_JP017_S2_RH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSolicitud_JP017_S2_RH2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        JPSolicitud_JP017_S2_RH2Layout.setVerticalGroup(
            JPSolicitud_JP017_S2_RH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSolicitud_JP017_S2_RH2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(LbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPSolicitud_JP017_S2_RH1Layout = new javax.swing.GroupLayout(JPSolicitud_JP017_S2_RH1);
        JPSolicitud_JP017_S2_RH1.setLayout(JPSolicitud_JP017_S2_RH1Layout);
        JPSolicitud_JP017_S2_RH1Layout.setHorizontalGroup(
            JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                .addGroup(JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(Btn2_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(JPSolicitud_JP017_S2_RH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        JPSolicitud_JP017_S2_RH1Layout.setVerticalGroup(
            JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblAsunto)
                .addGap(18, 18, 18)
                .addComponent(JPSolicitud_JP017_S2_RH2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Btn2_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Esta solicitud la aprobaste");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Btn1_JF017_S2_RH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(200, 200, 200)))
                .addComponent(JlLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 157, Short.MAX_VALUE)
                .addComponent(JPSolicitud_JP017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Btn1_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JlLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(JPSolicitud_JP017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        add(jPanel2, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF017_S2_RH1;
    public javax.swing.JButton Btn2_JF017_S2_RH1;
    public javax.swing.JPanel JPSolicitud_JP017_S2_RH1;
    public javax.swing.JPanel JPSolicitud_JP017_S2_RH2;
    public javax.swing.JLabel JlLogo1;
    public javax.swing.JLabel LbNotas;
    public javax.swing.JLabel LblAsunto;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
