/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

/**
 *
 * @author LENOVO
 */
public class JP027_2_S3_RH extends javax.swing.JPanel {

    /**
     * Creates new form JP027_2_S3_RH
     */
    public JP027_2_S3_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Nombre_JP027_S3_RH = new javax.swing.JLabel();
        JL_fecha_JP027_S3_RH = new javax.swing.JLabel();
        JL_ID_JP027_S3_RH = new javax.swing.JLabel();
        JL_image_JP027_S3_RH = new javax.swing.JLabel();
        btn_01_JP027_S3_RH = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        JL_Nombre_JP027_S3_RH.setBackground(new java.awt.Color(0, 102, 102));
        JL_Nombre_JP027_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JL_Nombre_JP027_S3_RH.setForeground(new java.awt.Color(0, 102, 102));
        JL_Nombre_JP027_S3_RH.setText("Nombre:");

        JL_fecha_JP027_S3_RH.setBackground(new java.awt.Color(0, 102, 102));
        JL_fecha_JP027_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JL_fecha_JP027_S3_RH.setForeground(new java.awt.Color(0, 102, 102));
        JL_fecha_JP027_S3_RH.setText("Fecha:");

        JL_ID_JP027_S3_RH.setBackground(new java.awt.Color(0, 102, 102));
        JL_ID_JP027_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JL_ID_JP027_S3_RH.setForeground(new java.awt.Color(0, 102, 102));
        JL_ID_JP027_S3_RH.setText("ID");

        btn_01_JP027_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn_01_JP027_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEditColor2.png"))); // NOI18N
        btn_01_JP027_S3_RH.setText("jButton1");
        btn_01_JP027_S3_RH.setBorderPainted(false);
        btn_01_JP027_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_01_JP027_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JL_image_JP027_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JL_Nombre_JP027_S3_RH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(JL_fecha_JP027_S3_RH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JL_ID_JP027_S3_RH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btn_01_JP027_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL_image_JP027_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(JL_Nombre_JP027_S3_RH)
                .addGap(13, 13, 13)
                .addComponent(JL_fecha_JP027_S3_RH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL_ID_JP027_S3_RH)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JL_ID_JP027_S3_RH;
    public javax.swing.JLabel JL_Nombre_JP027_S3_RH;
    public javax.swing.JLabel JL_fecha_JP027_S3_RH;
    public javax.swing.JLabel JL_image_JP027_S3_RH;
    public javax.swing.JButton btn_01_JP027_S3_RH;
    // End of variables declaration//GEN-END:variables
}
