/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import ux.Anuncios1;
import ux.EliminarAnunciosActuales;
import ux.PanelesInicializador;
import ux.VerSolicitudRechazada;

/**
 *
 * @author LENOVO
 */
public class JP021_S3_RH extends javax.swing.JPanel {
    
    
    
    private EliminarAnunciosActuales controlador;
    private PanelesInicializador str;

    public JButton getBtn1_JF021_S3_RH() {
        return Btn1_JF021_S3_RH;
    }

    public void setBtn1_JF021_S3_RH(JButton Btn1_JF021_S3_RH) {
        this.Btn1_JF021_S3_RH = Btn1_JF021_S3_RH;
    }

    public JButton getBtn2_JF021_S3_RH() {
        return Btn2_JF021_S3_RH;
    }

    public void setBtn2_JF021_S3_RH(JButton Btn2_JF021_S3_RH) {
        this.Btn2_JF021_S3_RH = Btn2_JF021_S3_RH;
    }

    public JButton getBtn3_JF021_S3_RH() {
        return Btn3_JF021_S3_RH;
    }

    public void setBtn3_JF021_S3_RH(JButton Btn3_JF021_S3_RH) {
        this.Btn3_JF021_S3_RH = Btn3_JF021_S3_RH;
    }

    public JPanel getJP021_S3_RH() {
        return PanelAnuncioView;
    }

    public void setJP021_S3_RH(JPanel JP021_S3_RH) {
        this.PanelAnuncioView = JP021_S3_RH;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JPanel getPanelAnuncioView() {
        return PanelAnuncioView;
    }

    public void setPanelAnuncioView(JPanel PanelAnuncioView) {
        this.PanelAnuncioView = PanelAnuncioView;
    }
    
    
    
    
    

    public JP021_S3_RH(EliminarAnunciosActuales controlador) {
        initComponents();
        this.controlador = controlador;
        
        str = new PanelesInicializador();
        
         // Establecer el valor de str aquí después de haberlo creado
        str.setJP021_S3_RH(this);
    }
    
    
    
    public JP021_S3_RH(Anuncios1 controlador) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001 = new javax.swing.JPanel();
        Btn1_JF021_S3_RH = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelAnuncioView = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn3_JF021_S3_RH = new javax.swing.JButton();
        Btn2_JF021_S3_RH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        JP001.setBackground(new java.awt.Color(255, 255, 255));
        JP001.setMaximumSize(new java.awt.Dimension(1120, 640));
        JP001.setMinimumSize(new java.awt.Dimension(1120, 640));
        JP001.setPreferredSize(new java.awt.Dimension(1120, 640));

        Btn1_JF021_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF021_S3_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF021_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector (1).png"))); // NOI18N
        Btn1_JF021_S3_RH.setBorderPainted(false);
        Btn1_JF021_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Anuncios actuales");

        PanelAnuncioView.setBackground(new java.awt.Color(255, 255, 255));
        PanelAnuncioView.setAutoscrolls(true);
        PanelAnuncioView.setMaximumSize(new java.awt.Dimension(486, 407));
        PanelAnuncioView.setMinimumSize(new java.awt.Dimension(486, 407));
        PanelAnuncioView.setName(""); // NOI18N
        PanelAnuncioView.setPreferredSize(new java.awt.Dimension(486, 486));
        PanelAnuncioView.setLayout(new javax.swing.BoxLayout(PanelAnuncioView, javax.swing.BoxLayout.LINE_AXIS));

        kGradientPanel1.setkEndColor(new java.awt.Color(200, 232, 232));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/line.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(200, 232, 232));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(200, 232, 232), new java.awt.Color(200, 232, 232), new java.awt.Color(200, 232, 232), new java.awt.Color(200, 232, 232)));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("¿Estás seguro de eliminar el anuncio?");

        Btn3_JF021_S3_RH.setBackground(new java.awt.Color(200, 232, 232));
        Btn3_JF021_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no.png"))); // NOI18N
        Btn3_JF021_S3_RH.setBorderPainted(false);
        Btn3_JF021_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Btn2_JF021_S3_RH.setBackground(new java.awt.Color(200, 232, 232));
        Btn2_JF021_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ci.png"))); // NOI18N
        Btn2_JF021_S3_RH.setBorderPainted(false);
        Btn2_JF021_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn2_JF021_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Btn3_JF021_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn3_JF021_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn2_JF021_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("¿Deseas hacer algún cambio?");

        javax.swing.GroupLayout JP001Layout = new javax.swing.GroupLayout(JP001);
        JP001.setLayout(JP001Layout);
        JP001Layout.setHorizontalGroup(
            JP001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JP001Layout.createSequentialGroup()
                .addGroup(JP001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn1_JF021_S3_RH)
                    .addGroup(JP001Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(PanelAnuncioView, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JP001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP001Layout.createSequentialGroup()
                        .addGroup(JP001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP001Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(165, 165, 165))
                            .addGroup(JP001Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel4)
                        .addGap(131, 131, 131))
                    .addGroup(JP001Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        JP001Layout.setVerticalGroup(
            JP001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(JP001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP001Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP001Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP001Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(JP001Layout.createSequentialGroup()
                        .addComponent(Btn1_JF021_S3_RH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelAnuncioView, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(JP001Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(JP001, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1_JF021_S3_RH;
    private javax.swing.JButton Btn2_JF021_S3_RH;
    private javax.swing.JButton Btn3_JF021_S3_RH;
    private javax.swing.JPanel JP001;
    private javax.swing.JPanel PanelAnuncioView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
