/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import ux.BuscadorPacientes;
import ux.PanelesInicializador;

/**
 *
 * @author 50369
 */
public class JP024_S3_AF extends javax.swing.JPanel {
    
    private BuscadorPacientes controlador;
    private PanelesInicializador str;

    public JButton getBtnVer() {
        return BtnVer;
    }

    public void setBtnVer(JButton BtnVer) {
        this.BtnVer = BtnVer;
    }

    public JButton getBtn1_JF024() {
        return btn1_JF024;
    }

    public void setBtn1_JF024(JButton btn1_JF024) {
        this.btn1_JF024 = btn1_JF024;
    }

    public JButton getBtn3_JF024() {
        return btn3_JF024;
    }

    public void setBtn3_JF024(JButton btn3_JF024) {
        this.btn3_JF024 = btn3_JF024;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTextField getTxtBuscar_JP024() {
        return txtBuscar_JP024;
    }

    public void setTxtBuscar_JP024(JTextField txtBuscar_JP024) {
        this.txtBuscar_JP024 = txtBuscar_JP024;
    }

    
    
   



    public JTable getJTable1() {
        return jTable1;
    }
    public JP024_S3_AF(BuscadorPacientes controlador) {
        initComponents();
        this.controlador = controlador;
        
        str = new PanelesInicializador();
        
         // Establecer el valor de str aquí después de haberlo creado
        str.setJP024_S3_AF(this);
    }
    /**
     * Creates new form JP024_S3_AF
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn3_JF024 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn1_JF024 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar_JP024 = new javax.swing.JTextField();
        BtnVer = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3_JF024.setBackground(new java.awt.Color(255, 255, 255));
        btn3_JF024.setForeground(new java.awt.Color(255, 255, 255));
        btn3_JF024.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N
        btn3_JF024.setBorderPainted(false);
        jPanel1.add(btn3_JF024, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 170, 90));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Escribe el nombre del paciente y seleccionalo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jTable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 540, 200));

        btn1_JF024.setBackground(new java.awt.Color(255, 255, 255));
        btn1_JF024.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a.PNG"))); // NOI18N
        btn1_JF024.setBorderPainted(false);
        jPanel1.add(btn1_JF024, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        jPanel2.setBackground(new java.awt.Color(200, 232, 232));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1120, -1));

        txtBuscar_JP024.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtBuscar_JP024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar_JP024ActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar_JP024, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 420, 50));

        BtnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dae.PNG"))); // NOI18N
        BtnVer.setBorderPainted(false);
        jPanel1.add(BtnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 90, 90));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscar_JP024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar_JP024ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar_JP024ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnVer;
    public javax.swing.JButton btn1_JF024;
    public javax.swing.JButton btn3_JF024;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField txtBuscar_JP024;
    // End of variables declaration//GEN-END:variables
}
