/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import ux.Ver_Expediente2;

/**
 *
 * @author LENOVO
 */
public class JP031_S3_RH extends javax.swing.JPanel {
     private Ver_Expediente2 controlador;
     
      public JLabel getJL_image_JF031_S3_RH() {
        return JL_image_JF031_S3_RH;
    }

    public JLabel getJL_Nombre_JF031_S3_RH() {
        return JL_Nombre_JF031_S3_RH;
    }

    public JLabel getJL_Edad_JF031_S3_RH() {
        return JL_Edad_JF031_S3_RH;
    }

    public JLabel getJL_Correo_JF031_S3_RH() {
        return JL_Correo_JF031_S3_RH;
    }

    public JLabel getJL_Telefono_JF031_S3_RH() {
        return JL_Telefono_JF031_S3_RH;
    }

    public JTextField getTxtEscribirMensaje_JP031_S3_RH() {
        return txtEscribirMensaje_JP031_S3_RH;
    }

    public JButton getBtn01_JP031_S3_RH() {
        return btn01_JP031_S3_RH;
    }
    
    public JP031_S3_RH() {
        Ver_Expediente2 controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_Nombre_JF031_S3_RH = new javax.swing.JLabel();
        JL_image_JF031_S3_RH = new javax.swing.JLabel();
        JL_Edad_JF031_S3_RH = new javax.swing.JLabel();
        JL_Correo_JF031_S3_RH = new javax.swing.JLabel();
        JL_Telefono_JF031_S3_RH = new javax.swing.JLabel();
        txtEscribirMensaje_JP031_S3_RH = new javax.swing.JTextField();
        btn01_JP031_S3_RH = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        JL_Nombre_JF031_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JL_Nombre_JF031_S3_RH.setText("Nombre Persona");

        JL_image_JF031_S3_RH.setText("image");

        JL_Edad_JF031_S3_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        JL_Edad_JF031_S3_RH.setText("Edad:");

        JL_Correo_JF031_S3_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        JL_Correo_JF031_S3_RH.setText("Correo electrónico:");

        JL_Telefono_JF031_S3_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        JL_Telefono_JF031_S3_RH.setText("Teléfono:");

        txtEscribirMensaje_JP031_S3_RH.setBackground(new java.awt.Color(148, 177, 181));
        txtEscribirMensaje_JP031_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtEscribirMensaje_JP031_S3_RH.setForeground(new java.awt.Color(255, 255, 255));
        txtEscribirMensaje_JP031_S3_RH.setText("Escribir mensaje");

        btn01_JP031_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn01_JP031_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazao.png"))); // NOI18N
        btn01_JP031_S3_RH.setBorderPainted(false);
        btn01_JP031_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(JL_image_JF031_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(JL_Nombre_JF031_S3_RH)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JL_Correo_JF031_S3_RH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addComponent(JL_Edad_JF031_S3_RH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JL_Telefono_JF031_S3_RH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtEscribirMensaje_JP031_S3_RH, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn01_JP031_S3_RH)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(JL_Nombre_JF031_S3_RH))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JL_Edad_JF031_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_image_JF031_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_Correo_JF031_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JL_Telefono_JF031_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEscribirMensaje_JP031_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn01_JP031_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGap(34, 34, 34))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JL_Correo_JF031_S3_RH;
    public javax.swing.JLabel JL_Edad_JF031_S3_RH;
    public javax.swing.JLabel JL_Nombre_JF031_S3_RH;
    public javax.swing.JLabel JL_Telefono_JF031_S3_RH;
    public javax.swing.JLabel JL_image_JF031_S3_RH;
    public javax.swing.JButton btn01_JP031_S3_RH;
    public javax.swing.JTextField txtEscribirMensaje_JP031_S3_RH;
    // End of variables declaration//GEN-END:variables
}
