/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import keeptoo.KGradientPanel;
import ux.Menu_Administrador;
import ux.Menu_Secretaria;

/**
 *
 * @author 50369
 */
public class JP039_S3_RH extends javax.swing.JPanel {

      private Menu_Secretaria controlador;

    public JButton getBtn03_JF005_S2_AF() {
        return btn03_JF005_S2_AF;
    }

    public void setBtn03_JF005_S2_AF(JButton btn03_JF005_S2_AF) {
        this.btn03_JF005_S2_AF = btn03_JF005_S2_AF;
    }
 
    


    public JButton getBtn05_JF039_S3_RH() {
        return btn05_JF039_S3_RH;
    }

    public void setBtn05_JF039_S3_RH(JButton btn05_JF039_S3_RH) {
        this.btn05_JF039_S3_RH = btn05_JF039_S3_RH;
    }

    public JButton getBtn06_JF039_S3_RH() {
        return btn06_JF039_S3_RH;
    }

    public void setBtn06_JF039_S3_RH(JButton btn06_JF039_S3_RH) {
        this.btn06_JF039_S3_RH = btn06_JF039_S3_RH;
    }

    public JButton getBtn08_JF039_S3_RH() {
        return btn08_JF039_S3_RH;
    }

    public void setBtn08_JF039_S3_RH(JButton btn08_JF039_S3_RH) {
        this.btn08_JF039_S3_RH = btn08_JF039_S3_RH;
    }

    public JButton getBtn09_JF039_S3_RH() {
        return btn09_JF039_S3_RH;
    }

    public void setBtn09_JF039_S3_RH(JButton btn09_JF039_S3_RH) {
        this.btn09_JF039_S3_RH = btn09_JF039_S3_RH;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public KGradientPanel getkGradientPanel1() {
        return kGradientPanel1;
    }

    public void setkGradientPanel1(KGradientPanel kGradientPanel1) {
        this.kGradientPanel1 = kGradientPanel1;
    }

    public KGradientPanel getkGradientPanel2() {
        return kGradientPanel2;
    }

    public void setkGradientPanel2(KGradientPanel kGradientPanel2) {
        this.kGradientPanel2 = kGradientPanel2;
    }

    public JButton getBtn06_JF023_S3_RH() {
        return btn06_JF023_S3_RH;
    }

    public void setBtn06_JF023_S3_RH(JButton btn06_JF023_S3_RH) {
        this.btn06_JF023_S3_RH = btn06_JF023_S3_RH;
    }
    
   
    
    public JP039_S3_RH(Menu_Secretaria controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        btn08_JF039_S3_RH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn05_JF039_S3_RH = new javax.swing.JButton();
        btn06_JF039_S3_RH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn09_JF039_S3_RH = new javax.swing.JButton();
        btn06_JF023_S3_RH = new javax.swing.JButton();
        btn03_JF005_S2_AF = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));

        btn08_JF039_S3_RH.setBackground(new java.awt.Color(0, 153, 153));
        btn08_JF039_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log out.png"))); // NOI18N
        btn08_JF039_S3_RH.setBorderPainted(false);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(552, Short.MAX_VALUE)
                .addComponent(btn08_JF039_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(517, 517, 517))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn08_JF039_S3_RH, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 1200, 80));

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel2.setText("¡Aprende a utilizar el sistema!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 40, 170, 90));

        btn05_JF039_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn05_JF039_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnPerfil.png"))); // NOI18N
        btn05_JF039_S3_RH.setBorderPainted(false);
        jPanel1.add(btn05_JF039_S3_RH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 180));

        btn06_JF039_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn06_JF039_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSoli.png"))); // NOI18N
        btn06_JF039_S3_RH.setBorderPainted(false);
        jPanel1.add(btn06_JF039_S3_RH, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 150, 180));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("¿Qué desea realizar hoy secretari@?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        btn09_JF039_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn09_JF039_S3_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btn09_JF039_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnPacientes.png"))); // NOI18N
        btn09_JF039_S3_RH.setBorderPainted(false);
        jPanel1.add(btn09_JF039_S3_RH, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 160, 180));

        btn06_JF023_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn06_JF023_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSolicitudesInc.png"))); // NOI18N
        btn06_JF023_S3_RH.setBorder(null);
        btn06_JF023_S3_RH.setBorderPainted(false);
        jPanel1.add(btn06_JF023_S3_RH, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        btn03_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn03_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAnuncios.png"))); // NOI18N
        btn03_JF005_S2_AF.setBorderPainted(false);
        btn03_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03_JF005_S2_AFActionPerformed(evt);
            }
        });
        jPanel1.add(btn03_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, 150, 180));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn03_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03_JF005_S2_AFActionPerformed

    }//GEN-LAST:event_btn03_JF005_S2_AFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn03_JF005_S2_AF;
    public javax.swing.JButton btn05_JF039_S3_RH;
    public javax.swing.JButton btn06_JF023_S3_RH;
    public javax.swing.JButton btn06_JF039_S3_RH;
    public javax.swing.JButton btn08_JF039_S3_RH;
    public javax.swing.JButton btn09_JF039_S3_RH;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public keeptoo.KGradientPanel kGradientPanel1;
    public keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
