/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import ux.BuscadorPacientes;
import ux.Hints;
import ux.LimiteCaracteres;
import ux.PanelesInicializador;
import ux.RcetarMedicamentos;

/**
 *
 * @author LENOVO
 */
public class JP036_S3_AF extends javax.swing.JPanel {

    private RcetarMedicamentos controlador;
    private PanelesInicializador str;
    private Hints hint;
    private LimiteCaracteres Limite;

    public JButton getBtnagregar() {
        return btnagregar;
    }

    public void setBtnagregar(JButton btnagregar) {
        this.btnagregar = btnagregar;
    }

    public JButton getjButton1() {
        return btnagregar;
    }

    public void setjButton1(JButton jButton1) {
        this.btnagregar = jButton1;
    }

    public JButton getBtn1_JF036() {
        return btn1_JF036;
    }

    public void setBtn1_JF036(JButton btn1_JF036) {
        this.btn1_JF036 = btn1_JF036;
    }

    public JTextField getTxtBuscar_JP036() {
        return txtBuscar_JP036;
    }

    public void setTxtBuscar_JP036(JTextField txtBuscar_JP036) {
        this.txtBuscar_JP036 = txtBuscar_JP036;
    }


    public JTextField getTxtHorario_JP036_S3_AF() {
        return txtHorario_JP036_S3_AF;
    }

    public void setTxtHorario_JP036_S3_AF(JTextField txtHorario_JP036_S3_AF) {
        this.txtHorario_JP036_S3_AF = txtHorario_JP036_S3_AF;
    }

    public JTextField getTxtNombreMedicamento_JP036_S3_AF() {
        return txtNombreMedicamento_JP036_S3_AF;
    }

    public void setTxtNombreMedicamento_JP036_S3_AF(JTextField txtNombreMedicamento_JP036_S3_AF) {
        this.txtNombreMedicamento_JP036_S3_AF = txtNombreMedicamento_JP036_S3_AF;
    }


    public JButton getBtn3_JF012_A() {
        return btn3_JF012_A;
    }

    public void setBtn3_JF012_A(JButton btn3_JF012_A) {
        this.btn3_JF012_A = btn3_JF012_A;
    }


    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /*
    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }
    
    */
    

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JTextArea getTxtIndicaciones_JP036_S3_AF() {
        return TxtIndicaciones_JP036_S3_AF;
    }

    public void setTxtIndicaciones_JP036_S3_AF(String text) {
    TxtIndicaciones_JP036_S3_AF.setText(text);
}

    
    
    
    
    public JP036_S3_AF(RcetarMedicamentos controlador) {
        initComponents();
        this.controlador = controlador;
        
        str = new PanelesInicializador();
        
         // Establecer el valor de str aquí después de haberlo creado
        str.setJP036_S3_AF(this);
    }
    public JP036_S3_AF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn3_JF012_A = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreMedicamento_JP036_S3_AF = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHorario_JP036_S3_AF = new javax.swing.JTextField();
        txtBuscar_JP036 = new javax.swing.JTextField();
        btn1_JF036 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtIndicaciones_JP036_S3_AF = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 715));
        setMinimumSize(new java.awt.Dimension(1120, 715));
        setPreferredSize(new java.awt.Dimension(1120, 715));
        setLayout(new java.awt.CardLayout());

        jPanel3.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel3.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel3.setPreferredSize(new java.awt.Dimension(1120, 640));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 715));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 715));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 715));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3_JF012_A.setBackground(new java.awt.Color(255, 255, 255));
        btn3_JF012_A.setForeground(new java.awt.Color(255, 255, 255));
        btn3_JF012_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        btn3_JF012_A.setBorder(null);
        btn3_JF012_A.setBorderPainted(false);
        jPanel1.add(btn3_JF012_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(200, 232, 232));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meds 1.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 190));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 350, 720));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel1.setText("Busca un padecimiento, para ver una receta predeterminada");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));
        jPanel1.add(txtNombreMedicamento_JP036_S3_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 420, 30));

        btnagregar.setBackground(new java.awt.Color(148, 177, 181));
        btnagregar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnagregar.setText("Enviar Receta");
        btnagregar.setBorderPainted(false);
        btnagregar.setFocusCycleRoot(true);
        btnagregar.setInheritsPopupMenu(true);
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 190, 50));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Recetar Medicamentos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Descripción");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Medicamento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));
        jPanel1.add(txtHorario_JP036_S3_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 410, 30));

        txtBuscar_JP036.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        txtBuscar_JP036.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar_JP036ActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar_JP036, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 420, 40));

        btn1_JF036.setBackground(new java.awt.Color(255, 255, 255));
        btn1_JF036.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a.PNG"))); // NOI18N
        btn1_JF036.setBorderPainted(false);
        btn1_JF036.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_JF036ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1_JF036, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Nombre del padecimiento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        TxtIndicaciones_JP036_S3_AF.setColumns(20);
        TxtIndicaciones_JP036_S3_AF.setRows(5);
        jScrollPane1.setViewportView(TxtIndicaciones_JP036_S3_AF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 420, 100));

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 170, 90));

        jPanel3.add(jPanel1, "card2");

        add(jPanel3, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscar_JP036ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar_JP036ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar_JP036ActionPerformed

    private void btn1_JF036ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_JF036ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1_JF036ActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea TxtIndicaciones_JP036_S3_AF;
    public javax.swing.JButton btn1_JF036;
    public javax.swing.JButton btn3_JF012_A;
    public javax.swing.JButton btnagregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtBuscar_JP036;
    private javax.swing.JTextField txtHorario_JP036_S3_AF;
    private javax.swing.JTextField txtNombreMedicamento_JP036_S3_AF;
    // End of variables declaration//GEN-END:variables
}
