/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

/**
 *
 * @author LENOVO
 */
public class JP041_S3_RH extends javax.swing.JPanel {

    /**
     * Creates new form JP041_S3_RH
     */
    public JP041_S3_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JLImagen_JP041_S3_RH = new javax.swing.JLabel();
        JLNombre_JP041_S3_RH = new javax.swing.JLabel();
        JLDescrip_JP041_S3_RH = new javax.swing.JLabel();
        JLFecha_JP041_S3_RH = new javax.swing.JLabel();
        btn1_JP041_S3_RH = new javax.swing.JButton();
        btn2_JP041_S3_RH = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));

        JLImagen_JP041_S3_RH.setText("imagen");

        JLNombre_JP041_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JLNombre_JP041_S3_RH.setText("Nombre");

        JLDescrip_JP041_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JLDescrip_JP041_S3_RH.setText("Descripción");

        JLFecha_JP041_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        JLFecha_JP041_S3_RH.setText("Fecha");

        btn1_JP041_S3_RH.setBackground(new java.awt.Color(246, 246, 246));
        btn1_JP041_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ci2.png"))); // NOI18N
        btn1_JP041_S3_RH.setBorderPainted(false);
        btn1_JP041_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn2_JP041_S3_RH.setBackground(new java.awt.Color(246, 246, 246));
        btn2_JP041_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no2.png"))); // NOI18N
        btn2_JP041_S3_RH.setBorderPainted(false);
        btn2_JP041_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JLImagen_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JLDescrip_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JLNombre_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLFecha_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn1_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLImagen_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLNombre_JP041_S3_RH)
                    .addComponent(JLFecha_JP041_S3_RH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLDescrip_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn2_JP041_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1_JP041_S3_RH))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLDescrip_JP041_S3_RH;
    public javax.swing.JLabel JLFecha_JP041_S3_RH;
    public javax.swing.JLabel JLImagen_JP041_S3_RH;
    public javax.swing.JLabel JLNombre_JP041_S3_RH;
    public javax.swing.JButton btn1_JP041_S3_RH;
    public javax.swing.JButton btn2_JP041_S3_RH;
    public javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
