/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import keeptoo.KGradientPanel;
import ux.CrearCita;
import ux.MBEliminarCita;
import ux.PanelesInicializador;

/**
 *
 * @author LENOVO
 */
public class JP043_1_S3_RH extends javax.swing.JPanel {

    private CrearCita controlador;
    private PanelesInicializador str;

    public JPanel getJP01_JF043_S3_RH() {
        return JP01_JF043_S3_RH;
    }

    public void setJP01_JF043_S3_RH(JPanel JP01_JF043_S3_RH) {
        this.JP01_JF043_S3_RH = JP01_JF043_S3_RH;
    }

    public JButton getBtn1_JF043_S3_RH() {
        return btn1_JF043_S3_RH;
    }

    public void setBtn1_JF043_S3_RH(JButton btn1_JF043_S3_RH) {
        this.btn1_JF043_S3_RH = btn1_JF043_S3_RH;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public KGradientPanel getkGradientPanel1() {
        return kGradientPanel1;
    }

    public void setkGradientPanel1(KGradientPanel kGradientPanel1) {
        this.kGradientPanel1 = kGradientPanel1;
    }

    public CrearCita getControlador() {
        return controlador;
    }

    public void setControlador(CrearCita controlador) {
        this.controlador = controlador;
    }

    public PanelesInicializador getStr() {
        return str;
    }

    public void setStr(PanelesInicializador str) {
        this.str = str;
    }

    public JTextField getTxtDia_JP043_S3_RH() {
        return txtDia_JP043_S3_RH;
    }

    public void setTxtDia_JP043_S3_RH(JTextField txtDia_JP043_S3_RH) {
        this.txtDia_JP043_S3_RH = txtDia_JP043_S3_RH;
    }

    public JTextField getTxtHoraInicio_JP043_S3_RH() {
        return txtHoraInicio_JP043_S3_RH;
    }

    public void setTxtHoraInicio_JP043_S3_RH(JTextField txtHoraInicio_JP043_S3_RH) {
        this.txtHoraInicio_JP043_S3_RH = txtHoraInicio_JP043_S3_RH;
    }

    public JTextField getTxtID_JP043_S3_RH() {
        return txtID_JP043_S3_RH;
    }

    public void setTxtID_JP043_S3_RH(String value) {
        txtID_JP043_S3_RH.setText(value);
    }

    public JTextField getTxtTerapeuta_JP043_S3_RH() {
        return txtTerapeuta_JP043_S3_RH;
    }

    public void setTxtTerapeuta_JP043_S3_RH(String value) {
        txtTerapeuta_JP043_S3_RH.setText(value);
    }

    public JButton getBtn01_JP043_S3_RH() {
        return btn01_JP043_S3_RH;
    }

    public void setBtn01_JP043_S3_RH(JButton btn01_JP043_S3_RH) {
        this.btn01_JP043_S3_RH = btn01_JP043_S3_RH;
    }

    public JButton getBtn_verEmpleados() {
        return Btn_verEmpleados;
    }

    public void setBtn_verEmpleados(JButton Btn_verEmpleados) {
        this.Btn_verEmpleados = Btn_verEmpleados;
    }

    public JButton getBtnverpacientes() {
        return Btnverpacientes;
    }

    public void setBtnverpacientes(JButton Btnverpacientes) {
        this.Btnverpacientes = Btnverpacientes;
    }

    public JP043_1_S3_RH(CrearCita controlador) {
        initComponents();
        this.controlador = controlador;

        str = new PanelesInicializador();

        // Establecer el valor de str aquí después de haberlo creado
        str.setJP043_1_S3_RH(this);
    }

    public JP043_1_S3_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1_JF043_S3_RH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JP01_JF043_S3_RH = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Btn_verEmpleados = new javax.swing.JButton();
        Btnverpacientes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTerapeuta_JP043_S3_RH = new javax.swing.JTextField();
        txtID_JP043_S3_RH = new javax.swing.JTextField();
        txtHoraInicio_JP043_S3_RH = new javax.swing.JTextField();
        txtDia_JP043_S3_RH = new javax.swing.JTextField();
        btn01_JP043_S3_RH = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 640));

        btn1_JF043_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn1_JF043_S3_RH.setForeground(new java.awt.Color(255, 255, 255));
        btn1_JF043_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector.png"))); // NOI18N
        btn1_JF043_S3_RH.setBorderPainted(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        JP01_JF043_S3_RH.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JP01_JF043_S3_RHLayout = new javax.swing.GroupLayout(JP01_JF043_S3_RH);
        JP01_JF043_S3_RH.setLayout(JP01_JF043_S3_RHLayout);
        JP01_JF043_S3_RHLayout.setHorizontalGroup(
            JP01_JF043_S3_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2235, Short.MAX_VALUE)
        );
        JP01_JF043_S3_RHLayout.setVerticalGroup(
            JP01_JF043_S3_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Crear cita");

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkGradientFocus(10);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        Btn_verEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        Btn_verEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rrrrr.png"))); // NOI18N
        Btn_verEmpleados.setBorderPainted(false);
        Btn_verEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Btnverpacientes.setBackground(new java.awt.Color(255, 255, 255));
        Btnverpacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnPacientes.png"))); // NOI18N
        Btnverpacientes.setBorderPainted(false);
        Btnverpacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("ID del paciente");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Hora de inicio");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Día");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("ID del Terapeuta");

        txtTerapeuta_JP043_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtTerapeuta_JP043_S3_RH.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtID_JP043_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtID_JP043_S3_RH.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHoraInicio_JP043_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtHoraInicio_JP043_S3_RH.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDia_JP043_S3_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtDia_JP043_S3_RH.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn01_JP043_S3_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn01_JP043_S3_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEnviar.png"))); // NOI18N
        btn01_JP043_S3_RH.setBorderPainted(false);
        btn01_JP043_S3_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoraInicio_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDia_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTerapeuta_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btn01_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 94, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHoraInicio_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDia_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtID_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTerapeuta_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn01_JP043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(Btnverpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(Btn_verEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(JP01_JF043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn1_JF043_S3_RH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(325, 325, 325)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(64, 64, 64))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(btn1_JF043_S3_RH))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                        .addComponent(JP01_JF043_S3_RH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btnverpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_verEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_verEmpleados;
    public javax.swing.JButton Btnverpacientes;
    public javax.swing.JPanel JP01_JF043_S3_RH;
    public javax.swing.JButton btn01_JP043_S3_RH;
    public javax.swing.JButton btn1_JF043_S3_RH;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    public javax.swing.JTextField txtDia_JP043_S3_RH;
    public javax.swing.JTextField txtHoraInicio_JP043_S3_RH;
    public javax.swing.JTextField txtID_JP043_S3_RH;
    public javax.swing.JTextField txtTerapeuta_JP043_S3_RH;
    // End of variables declaration//GEN-END:variables
}
